name: Voxelocity
main: io.github.willywonka125.voxelocity.Voxel
version: 0.2
commands:
  voxel:
    description: Main Voxelocity command 
    usage: /voxel
    aliases: [vox, vx, voxelocity]
  wild:
    description: Teleports you to a random location
    usage: /wild
