#Voxelocity config file
#Add essentials warps here. These will be shown in the teleportation menu, in order from top to bottom. 
#Case insensitive
warps:
  - portals
  - shop
  - wild
  - wild2
  - wild3
#ItemID to use in the inventory menu to enter the teleport menu. Must be valid ItemID.
tpMenuItem: 368
#ItemID to use for each warp.
warpItem: 276

#PocketChest configuration

#Maximum number of PocketChests a player can buy
maxChests: 1

#Maximum number of rows a player can buy, per chest (each row has 9 slots)
maxChestRows: 3

#Cost per row when buying chest. (Money taken from player's account via Vault)
costPerRow: 100